### ISSUE TITLE
Is it possible to extract shorelines with dask and rioxarray?

### ISSUE THREAD

**Issue by 2320sharon** [SatelliteShorelines/CoastSeg#148]
Currently extracting shorelines is very slow see issue Doodleverse/CoastSeg#119 . We've been brainstorming various ways to improve the speed of extract shorelines as well as making the memory utilization more efficient.

## Hypothesis
The way coastsat extracts shorelines is by looping through all the satellites then all the images for each satellite and returning a dictionary of the extracted shoreline information, which works for smaller amounts of images. The issue arises when there are hundreds or thousands of images which causes the dictionary containing the extracted shorelines to grow too large to fit efficiently in memory causing slowdowns or even crashing.

Members of our team have suggested a few theories one being that SDS_preprocess.preprocess_single could be a bottle neck since it is called in the extract shorelines loop. Another problem is that the figure of the extracted shorelines is being saved in the loop which is causing slowness due to the fact that saving files is a blocking operation.

There are a few constraints we have to keep in mind since coastseg is built with jupyter. Jupyter does not allow multiprocessing aka we cannot spawn additional processes. We can multithread using a separate package nest-asyncio to use asynchronous multithreading to perform multiple independent I/O operations concurrently which greatly improves performance. 

## How to Test Hypothesis

- [ ] Use [memory-profiler](https://pypi.org/project/memory-profiler/) or a better tool to figure out if SDS_shoreline.extract_shorelines is the cause of the bottleneck

- [ ] Use [memory-profiler](https://pypi.org/project/memory-profiler/) or a better tool to figure out if SDS_preprocess.preprocess_single is another significant bottleneck

## Tasks

- [ ] See if we can find a way to not make a massive dictionary all at once
- [ ] See if we can find a way to not save the extracted shoreline figures in a loop
- [ ] See if Dask will work with jupyter. Make sure that dask is only using threads otherwise jupyter will not work

## Experiment with rioxarray

A sample script that I've been working on to test if tif files can be loaded into rioxarrays. The idea is to use dask-rio-xarrays to replace the giant dictionaries and perform the operations in preprocess_single

```python
# installed from conda-forge
# rioxarray
# dask distributed
# not sure if the following packages are necessary
# xarray
# rasterio 

# Windows:
# import multiprocessing.popen_spawn_win32
import threading

import rioxarray
import xarray as xr
import numpy as np

cloud_mask_issue = False
mask_tif = r'C:\1_USGS\1_CoastSeg\1_official_CoastSeg_repo\CoastSeg\data\ID_yvk1_datetime06-05-23__06_57_26\L8\mask\2019-02-10-18-57-47_L8_ID_yvk1_datetime06-05-23__06_57_26_mask.tif'
ms_tif = r'C:\1_USGS\1_CoastSeg\1_official_CoastSeg_repo\CoastSeg\data\ID_yvk1_datetime06-05-23__06_57_26\L8\ms\2019-02-10-18-57-47_L8_ID_yvk1_datetime06-05-23__06_57_26_ms.tif'
pan_tif = r'C:\1_USGS\1_CoastSeg\1_official_CoastSeg_repo\CoastSeg\data\ID_yvk1_datetime06-05-23__06_57_26\L8\pan\2019-02-10-18-57-47_L8_ID_yvk1_datetime06-05-23__06_57_26_pan.tif'
fn=[ms_tif,pan_tif,mask_tif]

# Assuming fn_ms, fn_mask, satname and collection are already defined
# Use rioxarray.open_rasterio to read ms bands and cloud mask
da_ms = rioxarray.open_rasterio(fn[0], chunks={'band': 1, 'x': 1024, 'y': 1024},lock=threading.Lock())
da_mask = rioxarray.open_rasterio(fn[2], chunks={'x': 1024, 'y': 1024},lock=threading.Lock())

# Since the bands are a new dimension, you might not need to stack them
# If you want to transpose the data to have bands last, you can do so with the transpose method
da_ms = da_ms.transpose('y', 'x', 'band')

crs = da_ms.rio.crs
print("CRS:", crs)

# Finally, create the no data mask
im_nodata = da_ms.isnull()

# apply no_data mask
da_ms = da_ms.where(~im_nodata)
print(da_ms.data)

# Get the CRS string
crs_str = da_ms.rio.crs.to_string()

# Split the string on the colon and take the second part (the EPSG code)
epsg_code = crs_str.split(":")[1]

# Convert the EPSG code to an integer
epsg_code_int = int(epsg_code)
da_ms.attrs['CRS'] = epsg_code_int
print(da_ms.attrs)

# Select 0 band
da_band_0 = da_ms.isel(band=0)

# Convert to NumPy array
numpy_band_0 = da_band_0.values

print(f"numpy_band_0: {numpy_band_0}")
print(f"numpy_band_0.shape: {numpy_band_0.shape}")

# Convert to DataArray
cloud_mask = xr.DataArray(numpy_band_0 , dims=['y', 'x'], coords={'y': da_ms.y, 'x': da_ms.x})

# Add cloud_mask as a new data variable to the dataset
da_ms = da_ms.to_dataset(name='band_data')
da_ms['cloud_mask'] = cloud_mask


print(da_ms)


```

**Comment by 2320sharon** [comment]
Last Friday, I did some experimentation to learn how to load tif files with xarray.

## Context
In the code below I wanted to load two multispectral tifs that were downloaded by coastseg. I first loaded each file into its own `xarray.DataArray` , then loaded both the  `xarray.DataArray`  into `xarray.Dataset`.

## Code
### Step 1: Load the files
```
import os 
import rioxarray
import xarray as xr

filename1 = os.path.join(ms_path,'2018-12-03-18-39-48_L8_ID_kpd7_datetime08-28-23__01_47_44_ms.tif')
filename2 = os.path.join(ms_path,'2019-01-27-18-45-51_L8_ID_kpd7_datetime08-28-23__01_47_44_ms.tif')
```
### Step 2: Load the files into xarray.DataArray
```
# load the multispectral tifs into their own xarray.DataArray and name each  after the tif file
rds1 = rioxarray.open_rasterio(filename1)
rds1.name = '2018-12-03-18-39-48_L8_ID_kpd7_datetime08-28-23__01_47_44_ms.tif'
rds2 = rioxarray.open_rasterio(filename2)
rds2.name = '2019-01-27-18-45-51_L8_ID_kpd7_datetime08-28-23__01_47_44_ms.tif'
```
![image](https://github.com/Doodleverse/CoastSeg/assets/61564689/337430c8-20ff-4de6-8ee0-a2b5332c6236)

![image](https://github.com/Doodleverse/CoastSeg/assets/61564689/9bd902b2-7423-4fa0-9920-841fa4ff4c27)

### Step 3: Create the Dataset

```
# Create a Dataset out of both the xarray.DataArrays
ds = xr.Dataset({
    rds1.name: rds1,
    rds2.name: rds2
})

```
![image](https://github.com/Doodleverse/CoastSeg/assets/61564689/6d5c5f51-56f7-46e4-9e32-896f1b1a6bd0)

## Next Steps
Now that we know how to load the tif data into xarray Dataset's to we can perform operations across all the downloaded data at once, we will need to figure out how to use Dask to load the data, since the entire downloaded dataset will not fit into memory at once. Once we've figured that out we will need to map out the new workflow to processes the data using xarray functions.

**Comment by dbuscombe-usgs** [comment]
https://github.com/Doodleverse/CoastSeg/issues/131#issuecomment-1883865050

I think this should be in this Issue

**Comment by 2320sharon** [comment]
This functionality it going to be in CoastSeg Planet so I'm closing this issue here.
