### ISSUE TITLE
Feature Request: Add a button to allow a user to continue downloads

### ISSUE THREAD

**Issue by 2320sharon** [SatelliteShorelines/CoastSeg#226]
`coastsat_package` has been updated to allow downloads to continue if they were halted halfway through. I've tested this with an independent script and it works.
## Tasks

- [ ] figure out a mechanism that can be used to resume partial downloads
- [ ] show the user if downloads were partially completed
- [ ] have a mechanism for when a Roi with downloaded data is loaded

**Comment by 2320sharon** [comment]
This has been implemented at CoastSeg v1.21.1
