### ISSUE TITLE
Paper: Implement reviewer feedback

### ISSUE THREAD

**Issue by 2320sharon** [SatelliteShorelines/CoastSeg#239]
This issue is meant to track all updates related to the CoastSeg paper reviewer feedback
## Tasks

- [x] Implement feedback from reviewer one

- [x] Implement feedback from reviewer two

- [x] finalize the paper for Journal submission

**Comment by 2320sharon** [comment]
- [ ] Upload paper with reviewer feedback
