### ISSUE TITLE
Doc tree specifically for 'data' and 'sessions' 

### ISSUE THREAD

**Issue by fmemuir** [SatelliteShorelines/CoastSeg#260]
For [review 6683](https://github.com/openjournals/joss-reviews/issues/6683)

Small suggestion for the wiki, to make it clearer on the filing structure of where imagery and outputs are stored. The 'data' folder is mentioned in the Tutorials and Case Studies when bad images are filtered out, but it is only clear from the screenshots where the RGB folder of imagery sits and that this is the one to filter images out of. Additionally, the difference between 'data' and the output data stored in 'sessions' could be clearer; it's not immediately obvious that the extracted data is here. It's recommended that the wiki is given a short explanation (or even just a document tree fig) of where different files are being stored when the shorelines are extracted.

**Comment by 2320sharon** [comment]
Hi @fmemuir 

Thank you for the suggestions. These are excellent ideas. I'll update the wiki pages to explain why the downloaded imagery and sessions are separated and where the outputs go when the shoreline extraction process occurs. This should make the idea of using sessions easier for new users and help them understand where their data is stored.

## Tasks

- [ ] Explain the difference between 'data' and `sessions` in the `Getting Started`, Case Studies and `How to use Sessions` guides in the wiki

- [ ] Add a doctree to explain the file structure of a session to `How to use Sessions` and `How to Extract Shorelines` guides

- [ ] Explain how the downloaded data from 'data' is used in a session in the `Getting Started`, Case Studies and `How to use Sessions` guides in the wiki

- [ ] Add a doctree to the [How to Filter Bad Imagery](https://satelliteshorelines.github.io/CoastSeg/How-to-Filter-Out-Bad-Imagery/) and link to guide in [case_study_2](https://satelliteshorelines.github.io/CoastSeg/case_study_2/)

**Comment by 2320sharon** [comment]
@fmemuir 

I have implemented your feedback and made several enhancements to the documentation as detailed below:

- Screenshot Addition to Getting Started Guide: I've included a screenshot in the [getting started guide](https://satelliteshorelines.github.io/CoastSeg/getting-started/#:~:text=9.-,Download%20the%20ROIs,-Click%20the%20ROIs) to help users locate the RGB imagery for sorting.

- I updated the Getting Started Guide to clarify the difference between the ROIs in `CoastSeg/data` and `CoastSeg/sessions` and added a screenshot to show users where to find the shoreline detection images [here](https://satelliteshorelines.github.io/CoastSeg/getting-started/#:~:text=Extracting%20shorelines%20involves,this%20guide.)

- I updated the [How to Filter Bad Imagery](https://satelliteshorelines.github.io/CoastSeg/How-to-Filter-Out-Bad-Imagery/) and link to this guide in [case_study_2](https://satelliteshorelines.github.io/CoastSeg/case_study_2/)

- I updated the [How to Use Sessions](https://satelliteshorelines.github.io/CoastSeg/sessions/) guide to tell the user where the sessions are saved as well as how each session is related to ROIs in CoastSeg/data

- I also added a new page to the website called [What is in a Session](https://satelliteshorelines.github.io/CoastSeg/what-is-in-a-session/) that breaks down each kind of file in a session and  includes a doctree of the session contents.

Thank you for your feedback and I hope this will make sessions easier to understand. Please let me know if these changes work or if there needs to be any additional clarification.

Thank you again for reviewing CoastSeg and for your helpful feedback.

**Comment by fmemuir** [comment]
@2320sharon Great updates, really appreciate the added clarification!
